### ISSUE TITLE
Move 2718 to approved?

### ISSUE THREAD

**Issue by lightclient** [ethereum/eth1.0-specs#1]
My understanding was that [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) was approved for EFI in [ACD 92](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2092.md#22-eip-2718). Is that correct, or is "approved for EFI" something different?

**Comment by MadeofTin** [comment]
Yep. I can move it over. Thanks for finding the call link

**Comment by lightclient** [comment]
Thanks @MadeofTin!
