### ISSUE TITLE
[CFI Applied] EIP-2938: Account Abstraction

### ISSUE THREAD

**Issue by adietrichs** [ethereum/eth1.0-specs#10]
I would like to add [EIP-2938](https://eips.ethereum.org/EIPS/eip-2938) to the list of CFI applied EIPs. We asked about CFI inclusion for this EIP on the core devs meetings [97](https://github.com/ethereum/pm/issues/211) and [99](https://github.com/ethereum/pm/issues/219) and are currently waiting for client feedback. Thus, "CFI Applied" appears to correctly represent the current status of the EIP as per the [EIP process](https://github.com/ethereum/EIPs/blob/39181e8d376264d948963b33448a77fa38298164/EIPsForHardfork.md).

**Comment by timbeiko** [comment]
@adietrichs apologies for the delay. Where do you think it should be? I'm not sure I understand.

**Comment by timbeiko** [comment]
@adietrichs is this still relevant?
