### ISSUE TITLE
Move EIP-3074 to CFI

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eth1.0-specs#18]
I would like to move [EIP-3074] to the CFI status, for inclusion in a future hard fork. The specification is nearly complete; there's just some bikeshedding on the details.

[EIP-3074]: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3074.md

**Comment by timbeiko** [comment]
I've linked it in the "Applied" column based on the discussions we've had on AllCoreDevs :+1:
