### ISSUE TITLE
Add 2926 - Chunk-Based Code Merklization

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth1.0-specs#2]
I would like to add https://eips.ethereum.org/EIPS/eip-2926 to request it be considered for inclusion in a future hard fork.  cc @axic and @s1na

**Comment by timbeiko** [comment]
@pipermerriam is this still relevant? If so, do you think this should be considered for London or potentially a fork after?

**Comment by pipermerriam** [comment]
I think it's likely to be replaced by a "Chunk-Based Code **Verklization**" EIP, so yes, I this can be closed.
