### ISSUE TITLE
Make `baseFeePerGas` optional on pre-london blocks

### ISSUE THREAD

**Issue by lightclient** [ethereum/eth1.0-specs#210]
Per this discussion on discord: https://discord.com/channels/595666850260713488/804019759934078987/852562227780255754

**Comment by lightclient** [comment]
Apparently I can't assign myself to this issue since i'm not a member of the repo, but I'll handle this.

**Comment by timbeiko** [comment]
Should it be optional on pre-London blocks or should we make it clear it is simply not present, @lightclient ? The latter will allow users to know if the chain supports 1559 at a certain block, vs. there can be cases where a chain may have a base fee of 0.

**Comment by lightclient** [comment]
Ah sorry - poor wording there. I agree with you, it shouldn't exist pre-london. Thanks for the clarification.
