### ISSUE TITLE
Create issue labels matching the templates.

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eth1.0-specs#225]
With the merge of [issue templates](https://github.com/ethereum/eth1.0-specs/tree/master/.github/ISSUE_TEMPLATE) from the Quilt fork, we should recreate the same labels in this repository:

| Label Name | Description | Colour |
| -------------- | ---------------| -------- |
| `A-doc` | Area: documentation | `#FBCA04`
| `A-spec` | Area: specification | `#FBCA04`
| `A-tool` | Area: tooling | `#FBCA04`
|||
| `C-bug` | Category: this is a bug, deviation, or other problem. | `#C5DEF5`
| `C-enhance` | Category: a request for an improvement | `#C5DEF5`
| `C-question` | Category: this is a question or request for clarification | `#C5DEF5`
|||
| `E-easy` | Experience: easy, good for newcomers | `#0E8A16`
| `E-medium` | Experience: of moderate difficulty | `#0E8A16`
| `E-hard` | Experience: difficult, probably not for the faint of heart | `#0E8A16`

**Comment by SamWilsn** [comment]
_fixed a typo `s/T-tool/A-tool/` and added colours_

**Comment by poojaranjan** [comment]
Labels created. Please review and confirm.

**Comment by SamWilsn** [comment]
LGTM! Thank you :D

Do we want to remove/convert the existing labels in the repository as well?

**Comment by poojaranjan** [comment]
> Do we want to remove/convert the existing labels in the repository as well?

I think that would make sense. 

Hopefully, we're good to close this issue.

**Comment by SamWilsn** [comment]
> I think that would make sense.

:100: 

> Hopefully, we're good to close this issue.

I think so. Thanks again!
