### ISSUE TITLE
Enable github pages for this repository

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eth1.0-specs#226]
The rendered version of the specification is dumped into the [`gh-pages`](https://github.com/ethereum/eth1.0-specs/tree/gh-pages) branch.

 - [ ] Enable GitHub Pages.
 - [ ] Create an empty `.nojekyll` file in the root of the `gh-pages` branch.

**Comment by poojaranjan** [comment]
> GitHub Pages

![image](https://user-images.githubusercontent.com/29681685/124659517-0ae02880-de73-11eb-927b-f8a6d40cef45.png)

 https://ethereum.github.io/eth1.0-specs/

> Create an empty .nojekyll file in the root of the gh-pages branch.

https://github.com/ethereum/eth1.0-specs/blob/gh-pages/.nojekyll

@SamWilsn Let me know if it's done or anything is missed.

**Comment by SamWilsn** [comment]
Looks perfect.
