### ISSUE TITLE
Integer values and leading zeros

### ISSUE THREAD

**Issue by fvictorio** [ethereum/eth1.0-specs#286]
Methods like `eth_getBlockByNumber` expect an `Integer` value which is defined like this:

https://github.com/ethereum/eth1.0-specs/blob/ff5f44c7ce5ca6a166c24f64aa7b6a0af570aac9/json-rpc/spec.json#L1791

Notice that according to this pattern, a value like `"0x0123"` should be accepted, but if you try that in `geth` you get this error:

```
invalid argument 0: hex number with leading zero digits
```

In Hardhat we've decided to be as strict as geth with this, because otherwise users running code in Hardhat could find later that the same code doesn't work on geth. But accepting leading zeros makes sense because some tools generate hexadecimal strings padded with zeros (for example, to have an even length). See [this Hardhat issue](https://github.com/nomiclabs/hardhat/issues/1585) for an scenario where this happens.

I don't know what's the right thing to do here. Ideally geth, and any other client that does this, would be more permissive about it. The alternative is to make the spec iself match the scrict behavior, but I'd rather follow the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) here.

**Comment by lightclient** [comment]
@fvictorio I moved this to the api spec repo for further discussion, because this spec is deprecated.
