### ISSUE TITLE
[JSON-RPC] `eth_call` and `eth_estimateGas`'s params are incorrect

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/eth1.0-specs#289]
### What was wrong?

In the spec `eth_call` and `eth_estimateGas` take a `Transaction` content descriptor. This is not how clients work. The `Transaction` content descriptor has most (all?) fields `required`, and most should be optional instead.

**Comment by lightclient** [comment]
Hi @alcuadrado thank you for pointing this out. I have noted it in the new apis repo as this spec will soon be deprecated.

**Comment by alcuadrado** [comment]
Oh, I wasn't aware that there's a new repo! Thanks for opening the issue there. Should we close this one?

**Comment by lightclient** [comment]
Probably okay too!
