### ISSUE TITLE
Add 2584 - Convert to Binary Trie

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth1.0-specs#4]
I would like to add https://eips.ethereum.org/EIPS/eip-2584 to request it be considered for inclusion in a future hardfork. cc @gballet 

The linked EIP should not be considered representative of the technical specification as I believe @gballet is working on a new EIP based on the discussion thus far on the issue.

**Comment by timbeiko** [comment]
@pipermerriam @gballet is this still relevant? If so, should it be considered for London, or for a fork after that?

**Comment by pipermerriam** [comment]
I'll let @gballet confirm, but yes, this looks to be replaced by Verkle magic.

**Comment by timbeiko** [comment]
Cool, closing for now and will let Guillaume re-open if necessary.
